/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_openclwindow_nat_GPUBuffer */

#ifndef _Included_de_linusdev_openclwindow_nat_GPUBuffer
#define _Included_de_linusdev_openclwindow_nat_GPUBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_openclwindow_nat_GPUBuffer
 * Method:    _create
 * Signature: (JJIJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_de_linusdev_openclwindow_nat_GPUBuffer__1create
        (JNIEnv *, jobject, jlong, jlong, jint, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_GPUBuffer
 * Method:    _enqueueWriteBuffer
 * Signature: (JJZIIJ)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_openclwindow_nat_GPUBuffer__1enqueueWriteBuffer
        (JNIEnv *, jclass, jlong, jlong, jboolean, jint, jint, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_GPUBuffer
 * Method:    _delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_GPUBuffer__1delete
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_GPUBuffer
 * Method:    _deleteReturnStruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_GPUBuffer__1deleteReturnStruct
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
