/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_openclwindow_nat_OpenCLWindowJava */

#ifndef _Included_de_linusdev_openclwindow_nat_OpenCLWindowJava
#define _Included_de_linusdev_openclwindow_nat_OpenCLWindowJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1create
        (JNIEnv *, jobject);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _show
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1show
        (JNIEnv *, jobject, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _checkIfWindowShouldClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1checkIfWindowShouldClose
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _render
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1render
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _swapBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1swapBuffer
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1destroy
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1delete
        (JNIEnv *, jobject, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _setTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1setTitle
        (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _setSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1setSize
        (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _setBorderlessFullscreen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1setBorderlessFullscreen
        (JNIEnv *, jobject, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _setProgramCode
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1setProgramCode
        (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _createSharedRenderBuffer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1createSharedRenderBuffer
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _setBaseKernelArgs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1setBaseKernelArgs
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _setKernelArg
 * Signature: (JILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1setKernelArg__JILjava_nio_ByteBuffer_2I
        (JNIEnv *, jobject, jlong, jint, jobject, jint);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _setKernelArg
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1setKernelArg__JIJ
        (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _glfwSetInputMode
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1glfwSetInputMode
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    _glfwSetCursorPos
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava__1glfwSetCursorPos
        (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    isRawMouseMotionSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava_isRawMouseMotionSupported
        (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_openclwindow_nat_OpenCLWindowJava
 * Method:    getKeyName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_linusdev_openclwindow_nat_OpenCLWindowJava_getKeyName
        (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
